# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/ration_db
spring.datasource.username=root
spring.datasource.password=4255

# Driver
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
server.port=8081
